version: '3.4'

services:
  bookreservation:
    image: ${DOCKER_REGISTRY-}bookreservation
    build:
      context: .
      dockerfile: BookReservation/Dockerfile
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server_2022
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Test&Test
